types:
  - test
  - analyze

test:php-unit:
    type: test
    tags:
        - phpunit
    script:
        - composer install
        - phing run-test
    artifacts:
        paths:
            - tests/.report/**

analyze:sonar:
    type: analyze
    tags:
        - sonar-php
    script:
        - composer install
        - phing run-analyze
    dependencies:
        - test:php-unit
    cache:
        paths:
            - tests/.report/**
